# Generated by Django 5.0.2 on 2024-03-07 06:25

import cluedo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('pic', cluedo.models.FileField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('wins', models.IntegerField(default=0)),
                ('loss', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('ongoing', 'Ongoing'), ('finished', 'Finished')], default='open', max_length=30)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='cluedo.player')),
                ('players', models.ManyToManyField(blank=True, related_name='players_lobby', to='cluedo.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='won_game', to='cluedo.player')),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=1)),
                ('gameid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluedo.lobby')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluedo.player')),
            ],
        ),
    ]
