# Generated by Django 5.0.2 on 2024-04-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluedo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='turn',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
