# Generated by Django 5.0.2 on 2024-04-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluedo', '0002_lobby_turn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='lobby',
            name='answer',
            field=models.ManyToManyField(related_name='lobby_answers', to='cluedo.cards'),
        ),
    ]
