# Generated by Django 5.0.2 on 2024-04-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluedo', '0003_cards_lobby_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='type',
        ),
        migrations.AddField(
            model_name='cards',
            name='cardtype',
            field=models.CharField(choices=[('s', 'suspects'), ('w', 'weapons'), ('r', 'room')], default='s', max_length=30),
        ),
    ]
