# Generated by Django 5.0.2 on 2024-04-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluedo', '0004_remove_cards_type_cards_cardtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='cards',
            field=models.ManyToManyField(related_name='card_stack', to='cluedo.cards'),
        ),
    ]
